title: Class2 Editing

description: >
  New Website for Class Learning

author:
  name: Lon
  email: loncom5050@gmail.com

nav_pages:
  - about.md
  - contact.md

max-width: 800px

show_excerpts: true
show_rss_feed: true
show_github_link: true

plugins:
  - jekyll-feed
  - jekyll-seo-tag

content_selector: div.post-content,div.home
